In [1]:
import numpy as np

### Boolean Indexing

In [4]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x[x>5]

array([6, 7, 8, 9])

In [6]:
x = np.array([1,np.nan,2,3,np.nan])

In [7]:
x

array([ 1., nan,  2.,  3., nan])

In [8]:
x[~np.isnan(x)]

array([1., 2., 3.])

### Advanced indexing

In [22]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [23]:
i = np.array([1,1,3,8,5]) # array of required indexes
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [24]:
a = a.reshape(3,4)
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [26]:
i = np.array([[0,1],
             [1,2]])

j = np.array([[2,1],
             [3,3]])

a[i,j]

# a([[0,2 1,1],
     [1,3 2,3]])
    
# Integer based Indexing

array([[  4,  25],
       [ 49, 121]], dtype=int32)

### Shape manupulation

In [14]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
x.ravel() # used to create flat arrays 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
x.resize((2,6)) # reshape function returns its element with modified shape ; whereas ndarray.resize() modifies by 
#first flattenig and then reshaping

In [18]:
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
x.reshape(3,-1) # when no. of rows rrequired are clear but not sure of number of columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Stacking of Arrays

In [27]:
a = np.floor(10*np.random.rand(2,2))
a

array([[6., 7.],
       [4., 9.]])

In [28]:
b = np.floor(10*np.random.rand(2,2))
b

array([[7., 5.],
       [4., 1.]])

In [31]:
np.vstack((a,b)) # vertical stacking of both the arrays  

array([[6., 7.],
       [4., 9.],
       [7., 5.],
       [4., 1.]])

In [32]:
np.hstack((a,b)) # horizontal stacking of both the arrays  

array([[6., 7., 7., 5.],
       [4., 9., 4., 1.]])

In [34]:
np.concatenate((a,b),axis=1) # array concantenation

array([[6., 7., 7., 5.],
       [4., 9., 4., 1.]])

In [40]:
np.transpose(a) # returns the transpose of the array

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Iterating Over Arrays

In [35]:
a = np.arange(12).reshape(3,4)
for x in np.nditer(a) :
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


### Insertion And Deletion

In [41]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.insert(x,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6,  7,  8,  9])

In [50]:
np.insert(x,1,[11,12,13],axis=1) # inserting along the column

array([[ 1, 11,  2,  3],
       [ 4, 12,  5,  6],
       [ 7, 13,  8,  9]])

In [51]:
np.delete(x,5) # deleting the 5th element

array([1, 2, 3, 4, 5, 7, 8, 9])

### numpy.unique

In [52]:
a = np.array([5,2,4,5,6,6,6,5,2,2,2,1,1])
a

array([5, 2, 4, 5, 6, 6, 6, 5, 2, 2, 2, 1, 1])

In [53]:
u,i,c = np.unique(a,return_index=True,return_counts=True)
print("Unique Elements :",u)
print("Index of Unique Elements:",u)
print("Count of each element:",c)

Unique Elements : [1 2 4 5 6]
Index of Unique Elements: [1 2 4 5 6]
Count of each element: [2 4 1 3 3]
