In [1]:
import numpy as np

### Array Operations in NumPy

In [2]:
#creating a 1-D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#arrays can also be created using python list or tuple; data type is deduced from type of element in the sequence

l = [1,2,3,4,5]
np_arr = np.array(l)
print(np_arr)

[1 2 3 4 5]


In [4]:
type(np_arr) # The most important object in numpy is N-Dimensional array type called 'ndarray'

numpy.ndarray

In [5]:
# Creating numpy array from numpy matrix

np_mat = np.mat('1,2;3,4;5,6')
np_mat

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
np_arr_mat = np.array(np_mat)
np_arr_mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# Type casting
np.array([1,2,3],dtype = 'float')

array([ 1.,  2.,  3.])

In [8]:
# Creating Arrays using structured Data types
student = np.dtype([('name','U20'),('age','i1'),('marks','f4')])
print(student)

[('name', '<U20'), ('age', 'i1'), ('marks', '<f4')]


In [9]:
a = np.array([('Ram',15,78),('Sunny',16,54)],dtype=student)
print(a)

[('Ram', 15, 78.0) ('Sunny', 16, 54.0)]


In [10]:
a[0] # accesing the records

('Ram', 15, 78.0)

In [11]:
# Creating 2-D arrays
arr = np.array([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.shape #returns rows x columns of the array

(2, 3)

In [13]:
arr.ndim # returns the dimensions of the matrix

2

In [14]:
arr.size #returns the total number of elements

6

In [15]:
arr.dtype

dtype('int32')

In [16]:
arr.reshape(3,2) # reshape the matrix  we need to ensure that the number of elements shouldfit the shape

array([[1, 2],
       [3, 4],
       [5, 6]])

### NumPy Important Functions

In [17]:
np.zeros((2,3)) # np.zeros() -- creates an array full of zeros with given shape 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.ones((2,3),dtype='i8') # np.ones() -- creates an array full of zeros with given shape 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [19]:
np.empty((2,3)) # creates an array with specified shape with random initial content

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
np.eye(6) # creates an identity matrix

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [21]:
np.arange(10,25,5) # creates array of sequence with specified first and last element with given step size

array([10, 15, 20])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

### Random Number Generation

In [23]:
print(np.random.rand(2,3)) # creates array of given shape with random values between 0 and 1

[[ 0.15024506  0.47092078  0.84257847]
 [ 0.30060002  0.53625726  0.17743645]]


In [24]:
print(np.random.randn(2,3)) # creates Normal Distributed array with  mean = 0 and std deviation  = 1

[[ 0.49698718  0.44386946 -0.60323712]
 [ 0.30239736  1.41877245  1.67905503]]


In [25]:
np.random.randint(1,100) # choses a random value over specified range

50

In [26]:
np.random.randint(1,7,20) # this will return 20 samples from a dice

array([1, 6, 2, 6, 3, 4, 3, 5, 6, 1, 4, 6, 6, 1, 1, 1, 4, 2, 6, 6])

### Arithmatic Operation

In [27]:
a = np.array([0,30,45,60,90])

In [28]:
print (np.sin(a*np.pi/180))

[ 0.          0.5         0.70710678  0.8660254   1.        ]


In [29]:
print (np.cos(a*np.pi/180))

[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]


In [31]:
print (np.arcsin(a*np.pi/180)) #sin inverse

[ 0.          0.55106958  0.90333911         nan         nan]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in arcsin
  if __name__ == '__main__':


In [32]:
b = np.array([-1.7,1.5,0.6])

In [33]:
np.floor(b) # floor operation

array([-2.,  1.,  0.])

In [35]:
np.ceil(b) # ceil operation

array([-1.,  2.,  1.])

In [36]:
a = np.arange(9,dtype=np.float).reshape(3,3) # 3x3 array

In [37]:
b = np.array([10,10,10])

In [38]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [39]:
b

array([10, 10, 10])

In [40]:
np.add(a,b)

array([[ 10.,  11.,  12.],
       [ 13.,  14.,  15.],
       [ 16.,  17.,  18.]])

In [41]:
np.subtract(a,b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [42]:
np.multiply(a,b)

array([[  0.,  10.,  20.],
       [ 30.,  40.,  50.],
       [ 60.,  70.,  80.]])

In [43]:
np.divide(a,b)

array([[ 0. ,  0.1,  0.2],
       [ 0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8]])

In [46]:
np.reciprocal(a)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  if __name__ == '__main__':


array([[        inf,  1.        ,  0.5       ],
       [ 0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ]])

In [47]:
c = np.array([10,100,1000])
c

array([  10,  100, 1000])

In [48]:
np.power(c,2)

array([    100,   10000, 1000000], dtype=int32)

In [49]:
d = np.array([1,2,3])
d

array([1, 2, 3])

In [50]:
np.power(c,d)

array([        10,      10000, 1000000000], dtype=int32)

In [51]:
np.mod(c,d)

array([0, 0, 1], dtype=int32)

In [53]:
e = np.arange(12).reshape(3,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
e.sum(axis=0) # adding the elements along column

array([12, 15, 18, 21])

In [55]:
e.sum(axis=1) # adding the elements along row

array([ 6, 22, 38])

### Indexing and Slicing

In [58]:
a = np.arange(10)
b = a[2:7:2] # a[start : stop : step]


In [59]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b

array([2, 4, 6])

In [61]:
a[5] # to pick a single element

5

In [62]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a[1:2,1:3] # a[row_sliced : col. sliced]

array([[5, 6]])

In [67]:
a[2,3] # a[3rd row,4th col]

11

In [68]:
a[:,1] # all rows elements from first col

array([1, 5, 9])

In [73]:
a[1,...] # all items in second row

array([4, 5, 6, 7])

In [72]:
a[...,1]  # all items in 2nd col

array([1, 5, 9])